### ISSUE TITLE
请问一下对于微小目标使用什么模型结构较好？

### ISSUE THREAD

**Issue by Akiy071** [chaizwj/yolov8#3]
数据集目标检测框的宽高占总图像比例0.02之间，请问有什么tricks比较能够提高检出率？目前mAp0.48左右，非常期待您的答复。
![labels](https://github.com/user-attachments/assets/b4d526d0-af8e-4982-a8b4-92a158f5d622)

**Comment by chaizwj** [comment]
我的经验来看，可以对采用数据增强，比如翻转切割之类的，再试试看效果。具体也要多看看论文，看看有什么新的创新点

**Comment by Akiy071** [comment]
好的佬，谢谢您的建议。
